scholar:
        style: apa
        sort_by: year,month
        order: descending,descending
        bibliography_template: bib

collections:
        projects:
                output: false
                sort_by: chocolate
        teachings:
                output: false
