scholar:
        style: chicago-fullnote-bibliography
        sort_by: year,month
        order: descending,descending
        group_by: year
        group_order: descending
        bibliography_template: bib
